/*
 * generated by Xtext
 */
package jp.hishidama.xtext.dmdl_editor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DMDLUiModule extends jp.hishidama.xtext.dmdl_editor.ui.AbstractDMDLUiModule {
	public DMDLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
