/*
 * generated by Xtext
 */
package jp.hishidama.xtext.dmdl_editor.ui.contentassist

import jp.hishidama.xtext.dmdl_editor.ui.contentassist.AbstractDMDLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class DMDLProposalProvider extends AbstractDMDLProposalProvider {
}
