/*
* generated by Xtext
*/
package jp.hishidama.xtext.dmdl_editor.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DMDLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("jp/hishidama/xtext/dmdl_editor/parser/antlr/internal/InternalDMDL.tokens");
	}
}
