/*
 * first generated by Xtext
 */
package jp.hishidama.xtext.dmdl_editor.formatting;

import jp.hishidama.xtext.dmdl_editor.services.DMDLGrammarAccess;

import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;
import org.eclipse.xtext.xbase.lib.Extension;

import com.google.inject.Inject;

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#formatting on how and
 * when to use it
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an
 * example
 */
public class DMDLFormatter extends AbstractDeclarativeFormatter {
	@Inject
	@Extension
	private DMDLGrammarAccess grammarAccess;

	@Override
	protected void configureFormatting(FormattingConfig c) {
		DMDLFormatterUtil.configureFormatting(c, grammarAccess);
	}
}
