/*
 * first generated by Xtext
 */
package jp.hishidama.xtext.dmdl_editor.ui.labeling;

import jp.hishidama.xtext.dmdl_editor.dmdl.Attribute;
import jp.hishidama.xtext.dmdl_editor.dmdl.AttributeList;
import jp.hishidama.xtext.dmdl_editor.dmdl.ModelDefinition;
import jp.hishidama.xtext.dmdl_editor.dmdl.ModelReference;
import jp.hishidama.xtext.dmdl_editor.dmdl.Property;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.jdt.ui.ISharedImages;
import org.eclipse.jdt.ui.JavaUI;
import org.eclipse.swt.graphics.Image;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
public class DMDLLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public DMDLLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	protected Object text(AttributeList a) {
		return "<attributes>";
	}

	protected Object text(Attribute a) {
		return "@" + a.getName();
	}

	/*
	 * image
	 */

	protected Image image(ModelDefinition model) {
		return JavaUI.getSharedImages().getImage(ISharedImages.IMG_OBJS_CLASS);
	}

	protected Image image(ModelReference ref) {
		return image(ref.getName());
	}

	protected Image image(Property p) {
		return JavaUI.getSharedImages().getImage(ISharedImages.IMG_FIELD_PUBLIC);
	}

	protected Image _image(Attribute a) {
		return JavaUI.getSharedImages().getImage(ISharedImages.IMG_OBJS_ANNOTATION);
	}
}
