/*
 * generated by Xtext
 */
package jp.hishidama.xtext.dmdl_editor.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractDMDLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(jp.hishidama.xtext.dmdl_editor.dmdl.DmdlPackage.eINSTANCE);
		return result;
	}
}
